### PR TITLE
Creating new files from templates

### PR DESCRIPTION
**Pull request by ccheraa**
SASS is fixed too, and the extension is now compatible to package in [Pebble](https://github.com/evolvedbinary/pebble)

### CODE REVIEW

**Comment by adamretter** [comment]
1. I can't see any database side-bar launching the Browser app, it appears that the extension doesn't load:

Not sure if it is significant, but in the terminal where I ran `cd browser-app && yarn watch`, I see the following warnings:
```
WARNING in Circular dependency detected:
../pebble-extension/lib/browser/core.js -> ../pebble-extension/lib/browser/resource.js -> ../pebble-extension/lib/browser/core.js

WARNING in Circular dependency detected:
../pebble-extension/lib/browser/resource.js -> ../pebble-extension/lib/browser/core.js -> ../pebble-extension/lib/browser/resource.js

WARNING in ../node_modules/vscode-textmate/release/main.js 14:15-27
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-theme-registry.js
 @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-frontend-bindings.js
 @ ../node_modules/@theia/monaco/lib/browser/monaco-frontend-module.js
 @ ../node_modules/@theia/monaco/lib/browser/monaco-browser-module.js
 @ ./src-gen/frontend/index.js

WARNING in ../node_modules/vscode-textmate/release/main.js
Module Warning (from ../node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap '_suffix.js.map': Error: Can't resolve './_suffix.js.map' in '/Users/aretter/code/evolvedbinary/pebble-extension/node_modules/vscode-textmate/release'
 @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-theme-registry.js 56:24-50
 @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-frontend-bindings.js
 @ ../node_modules/@theia/monaco/lib/browser/monaco-frontend-module.js
 @ ../node_modules/@theia/monaco/lib/browser/monaco-browser-module.js
 @ ./src-gen/frontend/index.js

WARNING in ../node_modules/typescript-language-server/lib/commands.js
Module Warning (from ../node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/commands.ts': Error: Can't resolve '../src/commands.ts' in '/Users/aretter/code/evolvedbinary/pebble-extension/node_modules/typescript-language-server/lib'
 @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-contribution.js 83:17-67
 @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ../node_modules/reflect-metadata/Reflect.js
Module Warning (from ../node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file 'Reflect.ts': Error: Can't resolve './Reflect.ts' in '/Users/aretter/code/evolvedbinary/pebble-extension/node_modules/reflect-metadata'
 @ ./src-gen/frontend/index.js 3:0-27
```

2. I can't see any database side-bar launching the Electron app, it appears that the extension doesn't load:

Not sure if it is significant, but in the terminal where I ran `cd electron-app && yarn watch`, I see the following warnings:
```
WARNING in Circular dependency detected:
../pebble-extension/lib/browser/core.js -> ../pebble-extension/lib/browser/resource.js -> ../pebble-extension/lib/browser/core.js

WARNING in Circular dependency detected:
../pebble-extension/lib/browser/resource.js -> ../pebble-extension/lib/browser/core.js -> ../pebble-extension/lib/browser/resource.js

WARNING in ../node_modules/vscode-textmate/release/main.js 14:15-27
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js
 @ ../node_modules/@theia/monaco/lib/browser/textmate/index.js
 @ ../node_modules/@theia/typescript/lib/browser/javascript-language-config.js
 @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ../node_modules/vscode-textmate/release/main.js
Module Warning (from ../node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap '_suffix.js.map': Error: Can't resolve './_suffix.js.map' in '/Users/aretter/code/evolvedbinary/pebble-extension/node_modules/vscode-textmate/release'
 @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js 73:24-50
 @ ../node_modules/@theia/monaco/lib/browser/textmate/index.js
 @ ../node_modules/@theia/typescript/lib/browser/javascript-language-config.js
 @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ../node_modules/typescript-language-server/lib/commands.js
Module Warning (from ../node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/commands.ts': Error: Can't resolve '../src/commands.ts' in '/Users/aretter/code/evolvedbinary/pebble-extension/node_modules/typescript-language-server/lib'
 @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-contribution.js 83:17-67
 @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ../node_modules/reflect-metadata/Reflect.js
Module Warning (from ../node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file 'Reflect.ts': Error: Can't resolve './Reflect.ts' in '/Users/aretter/code/evolvedbinary/pebble-extension/node_modules/reflect-metadata'
 @ ./src-gen/frontend/index.js 3:0-27
```

**Comment by ccheraa** [comment]
Try starting over, clone the repo, run `yarn` at the root, `pebble-extension`, and then `browser-app`, before starting the web app

**Comment by adamretter** [comment]
Okay, I am now able to get the Electron and Browser apps to run :-)

A few issues still remain:
1. Clicking the `File` menu, and then `Connect...` does nothing.
2. You have to click `View` menu, and then `Pebble Connections` to get the side-bar to show.
    1. Could we have this open by default and above the Files menu in the sidebar?
    2. Could we also rename this to "Databases"?
3. If I create a connection and click on it, but the eXist server is not available or does not have the API installed I get nothing, on the console I see:
```
root ERROR caught: { code: 0, data: [ {} ] }
```
We should instead add an error popup dialog or something telling the user "Sorry, unable to connect to Pebble server at `http://localhost:8080`. Invalid response from the server".

**Comment by ccheraa** [comment]
[Delete Document(s)](https://trello.com/c/pHJWLjuZ/10-delete-documents)

**Comment by adamretter** [comment]
I am going to merge this because it mixes many things together, so it is becoming impossible to test without.

If you could provide distinct PR's from feature branches, that would help in future ;-)

**Pull request merged**
